name: Snyk Scan Dates

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  get-scan-dates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get install jq

    - name: Get Snyk Project ID
      env:
        SNYK_API_TOKEN: ${{ secrets.SNYK_TOKEN }}
        ORG_ID: 2238cc34-b2ee-4334-83b8-a26b53d1af6b
      run: |
        PROJECT_ID=$(curl -s -H "Authorization: token $SNYK_TOKEN" "https://snyk.io/api/v1/org/$ORG_ID/projects" | jq -r '.projects[] | select(.name=="snykgoof") | .id')
        echo "PROJECT_ID=${PROJECT_ID}" >> $GITHUB_ENV

    - name: Get Scan History
      env:
        SNYK_API_TOKEN: ${{ secrets.SNYK_TOKEN }}
        ORG_ID: 2238cc34-b2ee-4334-83b8-a26b53d1af6b
        PROJECT_ID: ${{ env.PROJECT_ID }}
      run: |
        curl -s -H "Authorization: token $SNYK_TOKEN" "https://snyk.io/api/v1/org/$ORG_ID/project/$PROJECT_ID/history" | jq '.[] | {created}'
