name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=.github/snyk.sarif
      - name: Process SARIF File
        run: bash .github/workflows/snyk-parse.sh
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .github/data/vulnerability_report_*.json
          git commit -m "Add Snyk vulnerability reports"
          git push
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      
