name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif

      - name: Parse Snyk SARIF output and update vulnerability details
        run: |
          # Define the SARIF file
          sarif_file="snyk.sarif"

          # Create an empty CSV file with headers if it doesn't exist
          csv_file="vulnerabilities.csv"
          if [ ! -f "$csv_file" ]; then
            echo "VulnerabilityName,Severity,Path,Line Number,Date Found" > $csv_file
          fi

          # Extract vulnerabilities from SARIF file
          vulnerabilities=$(jq -r '.runs[].results[] | [.ruleId, .level, .locations[].physicalLocation.artifactLocation.uri, .locations[].physicalLocation.region.startLine] | @csv' "$sarif_file")

          # Process each vulnerability
          while IFS=',' read -r ruleId level uri startLine; do
            # Check if vulnerability already exists in CSV
            existing_entry=$(grep -m 1 "^\"$ruleId\"," $csv_file)
            if [ -z "$existing_entry" ]; then
              # New vulnerability found, add it with today's date
              echo "\"$ruleId\",\"$level\",\"$uri\",\"$startLine\",\"$(date +%Y-%m-%d)\"" >> $csv_file
            else
              # Update existing entry (no need to change Date Found)
              :
            fi
          done <<< "$vulnerabilities"

      - name: Commit updated CSV file
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add vulnerabilities.csv
          git commit -m "Update vulnerabilities.csv with latest scan results"
          git push

      - name: Send Snyk details to Slack
        run: |
          echo "Sending notification to Slack..."
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "Snyk Vulnerability Report Details:\n\nTotal Vulnerabilities: '"$(jq '[.runs[].results[]] | length' snyk.sarif)"'\nHigh: '"$(jq '[.runs[].results[] | select(.level=="error")] | length' snyk.sarif)"'\nMedium: '"$(jq '[.runs[].results[] | select(.level=="warning")] | length' snyk.sarif)"'\nLow: '"$(jq '[.runs[].results[] | select(.level=="note")] | length' snyk.sarif)"'\nDetails:\n$(cat vulnerabilities.csv)"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
