name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test --json > snyk-result.json
            cat snyk-result.json
    
      - name: Format Slack message
        id: format-slack-message
        run: |
        vulnerabilities=$(jq -r '.vulnerabilities[] | "* \(.severity) - \(.title)\n  Path: \(.from[] | join(", "))\n  Info: \(.url)"' snyk-result.json)
        echo "$vulnerabilities" > vulnerabilities.txt
        summary=$(jq -r '"* \(.uniqueCount) unique vulnerabilities found\n* High: \(.highCount)\n* Medium: \(.mediumCount)\n* Low: \(.lowCount)"' snyk-result.json)
        echo "$summary" > summary.txt

      - name: Send Slack notification
        env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
        payload=$(jq -n --arg summary "$(cat summary.txt)" --arg vulnerabilities "$(cat vulnerabilities.txt)" \
        '{
          "text": "Snyk Vulnerability Report",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Snyk Vulnerability Report*\n\n*Summary:*\n\($summary)\n\n*Details:*\n\($vulnerabilities)"
              }
            }
          ]
        }')
        echo "$payload" > payload.json
        curl -X POST -H 'Content-type: application/json' --data "@payload.json" $SLACK_WEBHOOK_URL
