name: Snyk Security Scan

on: [push, pull_request]

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@v1.1.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --json-file-output=.github/data/snyk-result.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Analyze Snyk results
        run: |
          python - <<EOF
          import json

          # Load the Snyk results from the JSON file
          with open('.github/data/snyk-result.json', 'r') as f:
              data = json.load(f)

          # Initialize counters for different severity levels
          high_count = 0
          medium_count = 0
          low_count = 0

          # Iterate through the issues and count severities
          for issue in data['vulnerabilities']:
              if issue['severity'] == 'high':
                  high_count += 1
              elif issue['severity'] == 'medium':
                  medium_count += 1
              elif issue['severity'] == 'low':
                  low_count += 1

          # Print the results to a summary file
          with open('.github/data/snyk-summary.txt', 'w') as f:
              f.write(f"Total vulnerabilities: {len(data['vulnerabilities'])}\n")
              f.write(f"High severity vulnerabilities: {high_count}\n")
              f.write(f"Medium severity vulnerabilities: {medium_count}\n")
              f.write(f"Low severity vulnerabilities: {low_count}\n")

          print("Snyk analysis completed.")
          EOF

      - name: Print Snyk results
        run: cat .github/data/snyk-summary.txt

      - name: Upload Snyk JSON result
        uses: actions/upload-artifact@v2
        with:
          name: snyk-result
          path: .github/data/snyk-result.json

      - name: Upload Snyk Summary
        uses: actions/upload-artifact@v2
        with:
          name: snyk-summary
          path: .github/data/snyk-summary.txt
