name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Total Security Issues
        run: |
              length=$(cat snyk.sarif | jq '.runs[0].results | length')
              echo "RESULTS_LENGTH=$length" >> $GITHUB_ENV
      - name: Pass or Fail the Job
        run: |
              if ["$RESULTS_LENGTH" !=0 ]; then
                echo "Job Failed"
                exit 1
              else
                echo "Pass"
              fi

      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        if: always()
        with:
          payload: |
                {
                   "text": "*The Snyk scan result for repo , snykgoof, is : ${{ job.status }}* \n*Number of vulnerabilities : ${{ env.RESULTS_LENGTH }}* \n*Detail*: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
