name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Print the snyk sarif file
        run: cat snyk.sarif
      - name: Total Security Issues
        run: 
              length=$(cat snyk.sarif | jq '.runa[0].results | length')
              echo "RESULTS_LENGTH=$RESULTS_LENGTH" >> $GITHUB_ENV
