name: Example workflow for Node using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk.sarif
      - name: Total Security Issues
        run: |
              length=$(cat snyk.sarif | jq '.runs[0].results | length')
              echo "RESULTS_LENGTH=$length" >> $GITHUB_ENV
      - name: High
        run: |
              high=$(cat snyk.sarif | jq '.runs[0].results | map(select(.level == "error")) | length')
              echo "RESULTS_HIGH=$high" >> $GITHUB_ENV
      - name: Medium
        run: |
              medium=$(cat snyk.sarif | jq '.runs[0].results | map(select(.level == "warning")) | length')
              echo "RESULTS_MEDIUM=$medium" >> $GITHUB_ENV
      - name: Low
        run: |
              low=$(cat snyk.sarif | jq '.runs[0].results | map(select(.level == "note")) | length')
              echo "RESULTS_LOW=$low" >> $GITHUB_ENV
      
      - name: Extract commit URLs from SARIF file
        id: extract_commits
        run: |
          jq -r '.runs[].results[] | select(.level == "error") | .locations[].physicalLocation.artifactLocation.uri' snyk.sarif > commit_urls.txt

      - name: Calculate vulnerability age
        id: calculate_age
        run: |
          while IFS= read -r url; do
            # Extract repository and commit hash from URL
            repo=$(echo $url | cut -d '/' -f 4,5)
            commit_hash=$(echo $url | rev | cut -d '/' -f 1 | rev)
            
            # Fetch commit date
            commit_date=$(git log -1 --format="%ad" --date=iso8601-strict -- $commit_hash --pretty=tformat:"%cd" -- $repo)
            echo "RESULTS_COMMIT_Date=$commit_date" >> $GITHUB_ENV

            # Calculate age of vulnerability
            current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            commit_timestamp=$(date -d "$commit_date" +"%s" 2>/dev/null || date -jf "%Y-%m-%dT%H:%M:%S" "$commit_date" +"%s")
            current_timestamp=$(date -d "$current_date" +"%s")
            age=$((current_timestamp - commit_timestamp))
            age_days=$((age / 86400))
            echo "RESULTS_AGE=$age" >> $GITHUB_ENV
            echo "RESULTS_AGE_DAYS=$age_days" >> $GITHUB_ENV

            echo "Vulnerability introduced in commit $commit_hash of repository $repo is approximately $age_days days old."
          done < commit_urls.txt

      - name: Display vulnerability age
        run: echo "Vulnerability age calculated successfully."

        
      - name: Pass or Fail the Job
        run: |
              if ["$RESULTS_LENGTH" !=0 ]; then
                echo "Job Failed"
                exit 1
              else
                echo "Pass"
              fi

      - name: Send notification on Slack using Webhooks
        uses: slackapi/slack-github-action@v1.24.0
        if: always()
        with:
          payload: |
                {
                   "text": "*The Snyk scan result for repo , snykgoof, is : ${{ job.status }}* \n*Number of vulnerabilities : ${{ env.RESULTS_LENGTH }}* \n*High : ${{ env.RESULTS_HIGH }}* \n*Medium : ${{ env.RESULTS_MEDIUM }}* \n*Low : ${{ env.RESULTS_LOW }}* \n*Age : ${{ env.RESULTS_AGE }}* \n*Age_Days : ${{ env.RESULTS_AGE_DAYS }}* \n*Detail*: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
